accounts/urls.py
# accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myShop/urls.py


from .views import HomePageView, CustomersListView, OrdersListView, SearchView, ProductListView

from django.urls import path

app_name = 'myshop'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('customers/', CustomersListView.as_view(), name='customers'),
    path('orders/', OrdersListView.as_view(), name='orders'),
    path('search/', SearchView.as_view(), name='search'),
    path('product_list/', ProductListView.product_list, name='product_list'),
    path('<slug:category_slug>/', ProductListView.product_list,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>', ProductListView.product_detail,
         name='product_detail'),
]





shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('myShop.urls')),
    path('', include('myShop.urls', namespace='shop'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

myShop/models.py

# Create your models here.

from django.db import models
from django.urls import reverse


class Customer(models.Model):
    customer_id = models.AutoField("ID", primary_key=True)
    email = models.EmailField("E-mail", max_length=128)
    first_name = models.CharField("First Name", max_length=128)
    last_name = models.CharField("Last Name", max_length=128)
    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)
class Order(models.Model):
    order_id = models.AutoField("ID", primary_key=True)
    product = models.CharField("Product", max_length=128)
    order_date = models.DateField("Order Date")
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    def __str__(self):
        return '%s %s' % (self.order_id, self.product)

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True, verbose_name='Наименование')
    slug = models.CharField(max_length=150, db_index=True, unique=True, verbose_name='Ссылка')
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')
    uploaded = models.DateTimeField(auto_now=True, verbose_name='Изменён')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('myshop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
  quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
  update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from myShop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  form = CartAddProductForm(request.POST)
  if form.is_valid():
    cd = form.cleaned_data
    cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update']) # так как используется структура словаря, то добавление уже имеющегося продукта в корзину увеличит его количество
  return redirect('cart:cart_detail')

def cart_remove(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  cart.remove(product)
  return redirect('cart:cart_detail')

def cart_detail(request):
  cart = Cart(request)
  for item in cart:
    item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                      'update': True})
  return render(request, 'cart/detail.html', {'cart': cart})

myShop/views.py
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from myShop.models import Customer, Order, Category, Product
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm

class HomePageView(TemplateView):
    template_name = 'home.html'

class CustomersListView(ListView):
    template_name = "customer.html"
    model = Customer
    context_object_name = "list_of_all_customers"

class OrdersListView(ListView):
    template_name = "orders.html"
    model = Order
    context_object_name = "list_of_all_orders"

class SearchView(ListView):
    template_name = "search.html"
    model = Order
    context_object_name = "list_of_all_orders"

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query is None:
            return
        splittedQuery = query.rstrip().split()
        if len(splittedQuery) > 1:
            firstName = splittedQuery[0]
            lastName = splittedQuery[1]
            return Order.objects.filter(
                Q(customer__first_name__icontains=firstName) and Q(customer__last_name__icontains=lastName)
            ).order_by('order_date').reverse()
        return Order.objects.filter(
            Q(customer__first_name__icontains=query) | Q(customer__last_name__icontains=query)
        ).order_by('order_date').reverse()

class ProductListView(ListView):
    template_name = "base.html"
    model = Product
    context_object_name = "list_of_all_products"

    def product_list(request, category_slug=None):
        category = None
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'shop/product/list.html',
                      {
                          'category': category,
                          'categories': categories,
                          'products': products
                      })

    def product_detail(request, id, slug):
        product = get_object_or_404(Product, id=id, slug=slug, available=True)
        cart_product_form = CartAddProductForm()
        return render(request, 'shop/product/detail.html', {'product': product,
                                                            'cart_product_form': cart_product_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Корзина покупок
{% endblock %}

{% block content %}
  <h1>Корзина покупок</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Картинка</th>
        <th>Товар</th>
        <th>Обновить кол-во</th>
        <th>Удалить</th>
        <th>Кол-во</th>
        <th>Цена за шт</th>
        <th>Общая стоимость</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">В магазин</a>
    <a href="#" class="button">Оформить заказ</a>
  </p>
{% endblock %}

myShop/templates/shop/base.html
{% load static %}
<!--<!DOCTYPE html>-->
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}Мой магазин{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div id="header">
<a href="/" class="logo">Мой магазин</a>
</div>
<div id="subheader">
  <div class="cart">
    {% with total_items=cart|length %}
    {% if cart|length > 0 %}
    В корзине:
    <a href="{% url 'cart:cart_detail' %}">
      {{ total_items }} шт ,${{ cart.get_total_price }}
    </a>
    {% else %}
    Корзина пустая
    {% endif %}
    {% endwith %}
  </div>
</div>
<div id="content">
{% block content %}{% endblock %}
</div>
</body>
</html>

myShop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
<h1>{{ product.name }}</h1>
<h2>
<a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
</h2>
<p class="price">${{ product.price }}</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="В корзину">
    </form>
{{ product.description|linebreaks }}
</div>
{% endblock %}

myShop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
<h3>Категория</h3>
<ul>
<li {% if not category %}class="selected"{% endif %}>
<a href="{% url 'shop:product_list' %}">Все</a>
</li>
{% for c in categories %}
<li {% if category.slug == c.slug %}class="selected" {% endif %}>
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
{% endfor %}
</ul>
</div>
<div id="main" class="product-list">
<h1>{% if category %}{{ category.name }}{% else %}Товар{% endif %}</h1>
{% for product in products %}
<div class="item">
<a href="{{ product.get_absolute_url }}">
    <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}">
</a>
<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
<br>
${{ product.price }}
</div>
{% endfor %}
</div>
{% endblock %}

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Мой сайт</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
 <div class="wrapper">

     <header class="header">
         <div class="header__link__wrapper">
            <a class="header__link" href="/search">Поиск заказов</a>
            <a class="header__link" href="/orders">Все заказы</a>
             {% if user.is_authenticated %}
                {{ user.username }}
             {% else %}
                <a class="header__login__link" href="{% url 'login' %}">Войти</a>
             {% endif %}
         </div>
     </header>

     <main class="main">
 {% block content %}
      <!-- default content text (typically empty) -->
    {% endblock %}
     </main>
     <footer class="footer">
         <div class="footer__start__line">
             <span>Полезная информация</span>
         </div>
 <div class="footer__info_container">

 </div>
         <div class="footer__line"></div>
         <div class="social__media">
             <div class="social__media__icon_wrapper">
             <a href="#"><img class="social__media__icon" src="{% static 'img/telegram_icon.png' %}" alt="Django"></a>
              <a href="#"><img class="social__media__icon" src="{% static 'img/vk_icon.png' %}" alt="Django"></a>
              <a href="#"><img class="social__media__icon" src="{% static 'img/discord_icon.png' %}" alt="Django"></a>
             </div>
             <!--<span>Copyright © 2023-2024</span>
             <span>No rights reserved.</span>-->
         </div>

     </footer>
 </div>
</body>
<script src="{% static 'js/script.js' %}"></script>
</html>

templates/orders.html
{% extends "home.html" %}

{% block content %}
  <form action="{% url 'shop:search' %}" method="GET">
    {% csrf_token %}
    <input name="q" type="text" placeholder="Введите имя или фамилию...">
</form>
<h1>Список всех заказов:</h1>
<table>
    <tr>
        <th>Номер заказа</th>
        <th>Продукт</th>
        <th>Дата заказа</th>
        <th>Покупатель</th>
    </tr>
    {% for order in list_of_all_orders %}
    <tr>
        <td>{{ order.order_id }}</td>
        <td>{{ order.product }}</td>
        <td>{{ order.order_date }}</td>
        <td>{{ order.customer }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}







templates/search.html

{% extends "home.html" %}

{% block content %}
<title>Поиск заказов</title>
<form action="{% url 'shop:search' %}" method="GET">
    {% csrf_token %}
    <input name="q" type="text" placeholder="Введите имя или фамилию...">
</form>
<h1>Список заказов для:</h1>
<h2>{{ list_of_all_orders.0.customer }}</h2>
<table>
    <tr>
        <th>Заказанный продукт</th>
        <th>Дата заказа</th>
    </tr>
    {% for order in list_of_all_orders %}
    <tr>
        <td>{{ order.product }}</td>
        <td>{{ order.order_date }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}
















templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Регистрация нового пользователя</h2>
<form method="post">
  {% csrf_token %}
  <label for="{{ form.username.id_for_label }}">Имя:</label>
  {{ form.username }}
  <label for="{{ form.password1.id_for_label }}">Пароль:</label>
  {{ form.password1 }}
  <label for="{{ form.password2.id_for_label }}">Подтвердите пароль:</label>
  {{ form.password2 }}
  <button type="submit">Зарегистрировать</button>
</form>

</body>
</html>